### ISSUE TITLE
Whos is the lead in this project

### ISSUE THREAD

**Issue by azim254** [opensource254/opensource254.github.io#19]

**Comment by stannlee** [comment]
We can have a discussion on this here. As I've always said I don't want to do this alone. I want @opensource254/everyone  to have a chance to contribute

**Comment by brianngeywo** [comment]
Am good... but i dont even know where I fit @stannlee

**Comment by JoelKanyi** [comment]
For me I propose we vote, interested members wajitokeze

**Comment by miami78** [comment]
how about having multiple people lead, instead of one

**Comment by wilcox98** [comment]
Well  one person who can lead 
Not really a top tier programmer. Then i volunteer to lead the sprint meetings

**Comment by stannlee** [comment]
> For me I propose we vote, interested members wajitokeze

This is a great idea. We first need to identify those who are interested in contributing

**Comment by stannlee** [comment]
> Well one person who can lead
> Not really a top tier programmer. Then i volunteer to lead the sprint meetings

Thank you for this

**Comment by stannlee** [comment]
> how about having multiple people lead, instead of one

How would this happen? Please explain kidogo

**Comment by miami78** [comment]
well @stannlee , we can have close to three leads who make the final decisions on how the project is being run, like a board........ideas are being brought to them, they have a sit-down and discuss then approve.

**Comment by stannlee** [comment]
> well @stannlee , we can have close to three leads who make the final decisions on how the project is being run, like a board........ideas are being brought to them, they have a sit-down and discuss then approve.

Volunteer for this

**Comment by azim254** [comment]
watu wa  laravel  guide us through if we can replicate ile repo ya web template html qe can start from there

**Comment by stannlee** [comment]
> watu wa laravel guide us through if we can replicate ile repo ya web template html qe can start from there

If we are gonna use laravel, I suggest we use it for API only I'm not a fan of blade templating I like my Interfaces in javascript. Using laravel will give more people a chance to contribute too.

**Comment by miami78** [comment]
> > well @stannlee , we can have close to three leads who make the final decisions on how the project is being run, like a board........ideas are being brought to them, they have a sit-down and discuss then approve.
> 
> Volunteer for this

sure thing bro, I'm down on this

**Comment by BILLthebuilder** [comment]
> well @stannlee , we can have close to three leads who make the final decisions on how the project is being run, like a board........ideas are being brought to them, they have a sit-down and discuss then approve.

This sounds great

**Comment by stannlee** [comment]
All right two more volunteers

**Comment by brianngeywo** [comment]
am not a laravel guy... where's all the other people in this project?

**Comment by stannlee** [comment]
> am not a laravel guy... where's all the other people in this project?

We have not decided on the tech yet

**Comment by stannlee** [comment]
> > well @stannlee , we can have close to three leads who make the final decisions on how the project is being run, like a board........ideas are being brought to them, they have a sit-down and discuss then approve.
> 
> Volunteer for this

@azim254  I see a thumbs down here 👀

**Comment by azim254** [comment]
i did create a template from bootstrap [here](https://github.com/opensource254/WebTemplate) if we can work on this fine

**Comment by stannlee** [comment]
> i did create a template from bootstrap [here](https://github.com/opensource254/WebTemplate) if we can work on this fine

Sure I'll work with that on a dev branch and request your review

**Comment by stannlee** [comment]
You can follow the progress here #22 . This means that this convo has moved to the PR too. Thank you.
