### ISSUE TITLE
Slack link is no longer active

### ISSUE THREAD

**Issue by mukolweke** [opensource254/opensource254.github.io#29]
Think we need to update the slack channel link for devs to join
![Screenshot 2021-04-26 at 15 36 08](https://user-images.githubusercontent.com/15169261/116083353-31305d80-a6a5-11eb-96eb-41a45a843a53.png)

**Comment by StanleyMasinde** [comment]
Hi @mukolweke sorry for that. Here's a new link. We'll update that on the website 
[Slack](https://join.slack.com/t/opensource254/shared_invite/zt-kx7496s7-sFK7nBD77CGdIXbKDRJY8g)

**Comment by StanleyMasinde** [comment]
https://join.slack.com/t/opensource254/shared_invite/zt-pj6zdek2-eJdkJbBdFaAOvGZEePk8Xw

Updated link
